
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("articulo").del()
    .then(function () {
      // Inserts seed entries
      return knex("articulo").insert([
        {
          "id": 1,
          "id_categoria": 2,
          "id_producto": 4,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 5,
          "categoria": "Mujer",
          "producto": "Tobilleras",
          "descripcion": "Tobillera Mariposa",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 18,
          "peso": 50,
          "largo": 30,
          "ancho": 5,
          "imagen": "static/uploads/images/48003e76874c09ed3edd23a597c4784d993e.jpg",
          "existencia": 46,
          "en_oferta": false,
          "precio_costo": 200,
          "precio_venta": 400,
          "precio_oferta": 0,
          "activo": true
      },
      {
          "id": 2,
          "id_categoria": 2,
          "id_producto": 4,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 3,
          "categoria": "Mujer",
          "producto": "Tobilleras",
          "descripcion": "Tobillera corazon",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 10,
          "peso": 30,
          "largo": 30,
          "ancho": 5,
          "imagen": "static/uploads/images/150ac5435d2d0eb7cece60d051e54cbde2b0.jpeg",
          "existencia": 27,
          "en_oferta": true,
          "precio_costo": 120,
          "precio_venta": 300,
          "precio_oferta": 200,
          "activo": true
      },
      {
          "id": 3,
          "id_categoria": 2,
          "id_producto": 4,
          "id_proveedor": 1,
          "id_color": 3,
          "id_kilate": 3,
          "categoria": "Mujer",
          "producto": "Tobilleras",
          "descripcion": "Tobillera empedrada",
          "proveedor": "Prueba",
          "color": "Rosa",
          "kilate": 10,
          "peso": 50,
          "largo": 60,
          "ancho": 3,
          "imagen": "static/uploads/images/451c80b52092b4b3143f644ea7a111a83b3d.jpg",
          "existencia": 191,
          "en_oferta": true,
          "precio_costo": 100,
          "precio_venta": 300,
          "precio_oferta": 200,
          "activo": true
      },
      {
          "id": 4,
          "id_categoria": 3,
          "id_producto": 1,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 6,
          "categoria": "Hombre",
          "producto": "Cadenas",
          "descripcion": null,
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 20,
          "peso": 100,
          "largo": 70,
          "ancho": 7,
          "imagen": "static/uploads/images/089500e3a1c64a4ef0fcd7a83eae753c9026.jpeg",
          "existencia": 200,
          "en_oferta": null,
          "precio_costo": 400,
          "precio_venta": 600,
          "precio_oferta": null,
          "activo": true
      },
      {
          "id": 5,
          "id_categoria": 3,
          "id_producto": 5,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 2,
          "categoria": "Hombre",
          "producto": "Relojes",
          "descripcion": "Reloj Festina",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 8,
          "peso": 250,
          "largo": 20,
          "ancho": 20,
          "imagen": "static/uploads/images/b40bf7bfea3d4292f7629c4aa5176632389f.jpeg",
          "existencia": 300,
          "en_oferta": false,
          "precio_costo": 800,
          "precio_venta": 1100,
          "precio_oferta": 0,
          "activo": true
      },
      {
          "id": 6,
          "id_categoria": 3,
          "id_producto": 6,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 4,
          "categoria": "Hombre",
          "producto": "Medallas",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 14,
          "peso": 100,
          "largo": 0,
          "ancho": null,
          "imagen": "static/uploads/images/265fed107eae1f8c0dbefab7666218f088e6.jpg",
          "existencia": 200,
          "en_oferta": false,
          "precio_costo": 300,
          "precio_venta": 400,
          "precio_oferta": 0,
          "activo": true
      },
      {
          "id": 7,
          "id_categoria": 3,
          "id_producto": 6,
          "id_proveedor": 1,
          "id_color": 2,
          "id_kilate": 5,
          "categoria": "Hombre",
          "producto": "Medallas",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Blanco",
          "kilate": 18,
          "peso": 100,
          "largo": 0,
          "ancho": null,
          "imagen": "static/uploads/images/c39344ac75b374d4660ac71a3560d67789a2.jpg_640x640Q90",
          "existencia": 200,
          "en_oferta": true,
          "precio_costo": 300,
          "precio_venta": 500,
          "precio_oferta": 400,
          "activo": true
      },
      {
          "id": 8,
          "id_categoria": 1,
          "id_producto": 6,
          "id_proveedor": 1,
          "id_color": 2,
          "id_kilate": 3,
          "categoria": "Niños",
          "producto": "Medallas",
          "descripcion": "esto una prueba",
          "proveedor": "Prueba",
          "color": "Blanco",
          "kilate": 10,
          "peso": 100,
          "largo": 0,
          "ancho": null,
          "imagen": "static/uploads/images/e30f739bb617d07c8d96500b7c2be9e7a6b3.jpg_640x640Q90",
          "existencia": 200,
          "en_oferta": true,
          "precio_costo": 300,
          "precio_venta": 500,
          "precio_oferta": 400,
          "activo": true
      },
      {
          "id": 9,
          "id_categoria": 1,
          "id_producto": 5,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 3,
          "categoria": "Niños",
          "producto": "Relojes",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 10,
          "peso": 100,
          "largo": 0,
          "ancho": null,
          "imagen": "static/uploads/images/2db3d3aa3d5d9941b6efe43f5cc0c2b57094.jpeg",
          "existencia": 100,
          "en_oferta": false,
          "precio_costo": 600,
          "precio_venta": 800,
          "precio_oferta": 400,
          "activo": true
      },
      {
          "id": 10,
          "id_categoria": 1,
          "id_producto": 1,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 3,
          "categoria": "Niños",
          "producto": "Cadenas",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 10,
          "peso": 100,
          "largo": 50,
          "ancho": 5,
          "imagen": "static/uploads/images/0794b8442fa68d91c762a9e36d9a1a7822e5.jpeg",
          "existencia": 98,
          "en_oferta": true,
          "precio_costo": 200,
          "precio_venta": 300,
          "precio_oferta": 250,
          "activo": true
      },
      {
          "id": 11,
          "id_categoria": 2,
          "id_producto": 2,
          "id_proveedor": 1,
          "id_color": 3,
          "id_kilate": 3,
          "categoria": "Mujer",
          "producto": "Anillos",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Rosa",
          "kilate": 10,
          "peso": 30,
          "largo": 0,
          "ancho": 0,
          "imagen": "static/uploads/images/4823b50645309c4386bef6b2a8867897dfab.jpeg",
          "existencia": 200,
          "en_oferta": true,
          "precio_costo": 85,
          "precio_venta": 130,
          "precio_oferta": 100,
          "activo": true
      },
      {
          "id": 12,
          "id_categoria": 2,
          "id_producto": 1,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 4,
          "categoria": "Mujer",
          "producto": "Cadenas",
          "descripcion": "test",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 14,
          "peso": 200,
          "largo": 20,
          "ancho": 5,
          "imagen": "../static/uploads/images/0fca7fec9e3cbd52b548dc4fa8357007",
          "existencia": 50,
          "en_oferta": false,
          "precio_costo": 200,
          "precio_venta": 400,
          "precio_oferta": 0,
          "activo": true
      },
      {
          "id": 13,
          "id_categoria": 2,
          "id_producto": 1,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 4,
          "categoria": "Mujer",
          "producto": "Cadenas",
          "descripcion": "test",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 14,
          "peso": 200,
          "largo": 20,
          "ancho": 5,
          "imagen": "../static/uploads/images/03201740000373ad23677496709507a8",
          "existencia": 50,
          "en_oferta": false,
          "precio_costo": 200,
          "precio_venta": 400,
          "precio_oferta": 0,
          "activo": true
      },
      {
          "id": 14,
          "id_categoria": 2,
          "id_producto": 1,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 2,
          "categoria": "Mujer",
          "producto": "Cadenas",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 8,
          "peso": 0,
          "largo": 0,
          "ancho": 0,
          "imagen": "../static/uploads/images1/7b61d244875a35b9874d30763acdb55c",
          "existencia": 100,
          "en_oferta": false,
          "precio_costo": 100,
          "precio_venta": 200,
          "precio_oferta": 0,
          "activo": true
      },
      {
          "id": 15,
          "id_categoria": 2,
          "id_producto": 1,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 2,
          "categoria": "Mujer",
          "producto": "Cadenas",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 8,
          "peso": 0,
          "largo": 0,
          "ancho": 0,
          "imagen": "../static/uploads/images1/3a32129c1d065045aae951c696ae392d",
          "existencia": 100,
          "en_oferta": false,
          "precio_costo": 100,
          "precio_venta": 200,
          "precio_oferta": 0,
          "activo": true
      },
      {
          "id": 16,
          "id_categoria": 2,
          "id_producto": 1,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 2,
          "categoria": "Mujer",
          "producto": "Cadenas",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 8,
          "peso": 0,
          "largo": 0,
          "ancho": 0,
          "imagen": "../static/uploads/images1/00ce6980a42dc4ed648d47a309cbca51",
          "existencia": 100,
          "en_oferta": false,
          "precio_costo": 100,
          "precio_venta": 200,
          "precio_oferta": 0,
          "activo": true
      },
      {
          "id": 17,
          "id_categoria": 2,
          "id_producto": 1,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 2,
          "categoria": "Mujer",
          "producto": "Cadenas",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 8,
          "peso": 0,
          "largo": 0,
          "ancho": 0,
          "imagen": "/home/ariel/Programacion/Web/Express/tienda/static/uploads/images/c276cbcc5320c1f02140d9c0df2cb4921f9a.jpeg",
          "existencia": 100,
          "en_oferta": false,
          "precio_costo": 100,
          "precio_venta": 200,
          "precio_oferta": 0,
          "activo": true
      },
      {
          "id": 18,
          "id_categoria": 2,
          "id_producto": 1,
          "id_proveedor": 1,
          "id_color": 1,
          "id_kilate": 3,
          "categoria": "Mujer",
          "producto": "Cadenas",
          "descripcion": "",
          "proveedor": "Prueba",
          "color": "Amarillo",
          "kilate": 10,
          "peso": 100,
          "largo": 30,
          "ancho": 0,
          "imagen": "/home/ariel/Programacion/Web/Express/tienda/static/uploads/images/24c1c6d4e04ebd39b88ce152293b0056516c.jpeg",
          "existencia": 150,
          "en_oferta": false,
          "precio_costo": 400,
          "precio_venta": 0,
          "precio_oferta": 0,
          "activo": true
      }
      ]);
    });
};
